steps:
  - name: gcr.io/cloud-builders/docker
    id: Build training container image
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - -f
      - dockerfiles/train.dockerfile
      - -t
      - europe-west4-docker.pkg.dev/diabetic-classification-484510/container-registry/train:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push training container image
    args:
      - push
      - europe-west4-docker.pkg.dev/diabetic-classification-484510/container-registry/train:latest

options:
  logging: CLOUD_LOGGING_ONLY
